#!/bin/bash

if [ -z  "$PORT" ]; then
  PORT=80
fi

cat > /etc/nginx/sites-enabled/default <<EOF
server {
  root /var/www;
  listen ${PORT};
  server_name localhost;

  location / {
    index  index.html;
  }
}
EOF

cat > /var/www/index.html <<EOF
<html>
<head>
  <title>Nginx</title>
</head>
<body>
  <h1>Hey!</h1>
  <h1>I'm running on ${MARATHON_APP_ID}</h1>
</body>
</html>
EOF

exec nginx

